# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.7 # Note : tests are run in multiple versions of python by tox

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -U codecov

# Command to run tests, e.g. python setup.py test
script: tox

